Built-in modules

platform module

In [3]:
import platform

x = platform.system()
print(x)

#dir() function show a list of function name(variable name) in module
y = dir(platform)
print(y)

Windows
['_Processor', '_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_default_architecture', '_follow_symlinks', '_get_machine_win32', '_java_getprop', '_mac_ver_xml', '_node', '_norm_version', '_os_release_cache', '_os_release_candidates', '_parse_os_release', '_platform', '_platform_cache', '_sys_version', '_sys_version_cache', '_syscmd_file', '_syscmd_ver', '_uname_cache', '_unknown_as_blank', '_ver_stages', '_win32_ver', '_wmi', '_wmi_query', 'architecture', 'collections', 'freedesktop_os_release', 'functools', 'itertools', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'python_compiler', 'python_implementation', 'python_revision', 'python_version', 'python_version_tuple', 're', 'release', 'sys', 'system', 'system_alias', 'uname', 'uname_result', 

math moule

In [25]:
import math

x = math.ceil(2.2)
y = math.floor(5.56)
z = math.pi

print("ceiling value is ::",x)
print("Floor value is ::",y)
print("Pi values is ::",z)

print("The value of euler's number is :",math.e)

ceiling value is :: 3
Floor value is :: 5
Pi values is :: 3.141592653589793
The value of euler's number is : 2.718281828459045


Date module

In [18]:
import datetime

x = datetime.datetime.now()

y = datetime.datetime(2025,1,17)
print(x)

print(x.year)
print(x.strftime("%A"))

print(y)

2025-01-17 12:37:05.885710
2025
Friday
2025-01-17 00:00:00


strftime() method

In [26]:
import datetime

x = datetime.datetime.now()

print(x.strftime("%a"))
print(x.strftime("%A"))
print(x.strftime("%u"))#day in digit
print(x.strftime("%x"))#m-d-y
print(x.strftime("%X"))
print(x.strftime("%c"))#local version of datetime
print(x.strftime("%C"))#century
print(x.strftime("%W"))#week

Fri
Friday
5
01/17/25
12:57:59
Fri Jan 17 12:57:59 2025
20
02


os module

In [45]:
import os

"""os.mkdir("d:\\newdir1")
print("new directory is created")"""
#cwd current working directory
cwd = os.getcwd()
print("current working directory :",cwd)
#os name() method
print("os name :",os.name)

new directory is created
current working directory : d:\vidhi\Day 13 Task 13
os name : nt


In [51]:
import os

#write file, open the file
file = open("python.txt","w")
file.write("python 3.0 now avaible")
file.close()

#read file
file = open("pyhton.txt","r")
text = file.read()
print(text)

#popen() method
## popen() provides gateway and accesses the file directly
file = os.popen("pyhton.txt","w")
file.write("This is new")

What is Python?
Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.

It is used for:

web development (server-side),
software development,
mathematics,
system scripting.
What can Python do?
Python can be used on a server to create web applications.
Python can be used alongside software to create workflows.
Python can connect to database systems. It can also read and modify files.
Python can be used to handle big data and perform complex mathematics.
Python can be used for rapid prototyping, or for production-ready software development.


11

In [56]:
#rename the file
import os 

fd = "python.txt"
os.rename(fd,"python1.txt")
print("successfully rename")

successfully rename


In [ ]:
#majaor() method

import os

# Get the raw device number
"""device = os.stat("python.txt").st_dev

print("major device number is::", os.major(device))"""

'device = os.stat("python.txt").st_dev\n\nprint("major device number is::", os.major(device))'

In [19]:
import os

#print value of the environment variable key
print (os.getenv("square"))

None


In [21]:
#return a status of file
import os
print(os.lstat("python1.txt"))

os.stat_result(st_mode=33206, st_ino=562949954050184, st_dev=8546872986229500799, st_nlink=1, st_uid=0, st_gid=0, st_size=22, st_atime=1737110855, st_mtime=1737109667, st_ctime=1737109308)


In [29]:
#encode the file path

import os

encode = os.fsencode("D:\\vidhi\\Day 13 Task 13")
decode = os.fsdecode("D:\\vidhi\\Day 13 Task 13")
print("Encoded path :",encode)
print("decoded path",decode)

Encoded path : b'D:\\vidhi\\Day 13 Task 13'
decoded path D:\vidhi\Day 13 Task 13


Numpy library

In [31]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [46]:
import numpy as np

arr = np.array(42)

arr2 = np.array([[4,5,9],[7,5,4]])

arr3 = np.array([[[7,2,7],[5,4,1]],[[3,5,4],[4,8,2]]])

print(arr)
print(arr2)
print(arr3)

print(arr.ndim)
print(arr2.nbytes)
print(arr2.ndim)

#access the value
print("-------------------------------")
print(arr2[1])
print("-------------------------------")
print(arr3[0,1])
print("-------------------------------")
print(arr3[0,1,0])

print("-------------------------------")
print(arr3.dtype)

42
[[4 5 9]
 [7 5 4]]
[[[7 2 7]
  [5 4 1]]

 [[3 5 4]
  [4 8 2]]]
0
48
2
-------------------------------
[7 5 4]
-------------------------------
[5 4 1]
-------------------------------
5
-------------------------------
int64
-------------------------------
int64
